"""
Common Drawing Forms Generator
Comprehensive templates for bridge engineering drawings based on analysis of 184+ drawings
from the Filtered_Drawings collection.

Drawing Categories Identified:
1. General Arrangement Drawings (GAD)
2. Pier Details (Geometry & Reinforcement)
3. Abutment Details (Various Types)
4. Wing Wall Details
5. Bed Protection & Anchorage
6. Deck Slab Details
7. Guard Stone & Kerb Details
8. Cross Sections
9. Expansion Joint Details
10. Bearing Details
11. Foundation Details
12. False Work/Formwork
13. Culvert Details
14. Footbridge Details
15. Notes & Specifications

Author: Auto-generated by Drawing Collection Analyzer
Date: 2026-04-18
"""

from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass, field
from enum import Enum


class BridgeType(Enum):
    """Types of bridges supported."""
    SLAB_BRIDGE = "Slab Bridge"
    GIRDER_BRIDGE = "Girder Bridge"
    SUBMERSIBLE_BRIDGE = "Submersible Bridge"
    FOOTBRIDGE = "Footbridge"
    CULVERT = "Culvert"
    AQUEDUCT = "Aqueduct"


class AbutmentType(Enum):
    """Types of abutments."""
    CANTILEVER = "Cantilever Abutment"
    GRAVITY = "Gravity Abutment"
    COUNTERFORT = "Counterfort Abutment"
    wing_wall = "Wing Wall Abutment"


class PierType(Enum):
    """Types of piers."""
    SOLID_RECTANGULAR = "Solid Rectangular Pier"
    SOLID_CIRCULAR = "Solid Circular Pier"
    WALL_PIER = "Wall Pier"
    HAMMERHEAD = "Hammerhead Pier"
    TWIN_COLUMN = "Twin Column Pier"


@dataclass
class DrawingParameters:
    """Standard parameters for bridge drawings."""
    # Bridge geometry
    span_length: float
    number_of_spans: int
    carriage_width: float
    footpath_width: float
    
    # Levels
    rtl: float  # Road Top Level
    hfl: float  # High Flood Level
    bed_level: float
    foundation_level: float
    agl: float  # Average Ground Level
    
    # Pier parameters
    pier_width: float
    pier_depth: float
    pier_cap_height: float
    pier_cap_width: float
    pier_type: PierType = PierType.SOLID_RECTANGULAR
    
    # Abutment parameters
    abutment_width: float
    abutment_base_width: float
    abutment_height: float
    abutment_type: AbutmentType = AbutmentType.CANTILEVER
    
    # Slab parameters
    slab_thickness: float
    wearing_coat_thickness: float
    
    # Skew angle (for skewed bridges)
    skew_angle: float = 0.0
    
    # Materials
    concrete_grade: str = "M35"
    steel_grade: str = "Fe500"
    
    # Project info
    project_name: str = ""
    drawing_no: str = ""
    bridge_type: BridgeType = BridgeType.SLAB_BRIDGE
    
    # Wing wall parameters
    wing_wall_length: float = 3.0
    wing_wall_angle: float = 45.0
    wing_wall_height: float = 3.0
    
    # Bed protection
    bed_protection_length: float = 5.0
    bed_protection_thickness: float = 0.3
    
    # Foundation parameters
    footing_width: float = 4.0
    footing_depth: float = 1.0
    pile_diameter: float = 0.6
    pile_length: float = 12.0
    number_of_piles: int = 4


class CommonDrawingForms:
    """Templates for common bridge drawing forms."""
    
    @staticmethod
    def create_gad_elevation(params: DrawingParameters) -> Dict:
        """
        Generate General Arrangement Drawing - Elevation View.
        Common elements: spans, piers, abutments, water level, dimensions.
        """
        entities = []
        
        # Deck slab
        deck_start = 0
        deck_end = params.span_length * params.number_of_spans
        
        # Abutments
        abutment_left = {
            'type': 'RECTANGLE',
            'x': -params.abutment_width,
            'y': params.foundation_level,
            'width': params.abutment_width,
            'height': params.abutment_height,
            'layer': 'ABUTMENTS'
        }
        entities.append(abutment_left)
        
        # Spans
        for i in range(params.number_of_spans):
            span = {
                'type': 'LINE',
                'x1': i * params.span_length,
                'y1': params.rtl,
                'x2': (i + 1) * params.span_length,
                'y2': params.rtl,
                'layer': 'DECK'
            }
            entities.append(span)
        
        # Piers
        for i in range(1, params.number_of_spans):
            pier = {
                'type': 'RECTANGLE',
                'x': i * params.span_length - params.pier_width/2,
                'y': params.foundation_level,
                'width': params.pier_width,
                'height': params.pier_depth,
                'layer': 'PIERS'
            }
            entities.append(pier)
        
        # Abutment right
        abutment_right = {
            'type': 'RECTANGLE',
            'x': deck_end,
            'y': params.foundation_level,
            'width': params.abutment_width,
            'height': params.abutment_height,
            'layer': 'ABUTMENTS'
        }
        entities.append(abutment_right)
        
        # Water level (HFL)
        hfl_line = {
            'type': 'DASHED_LINE',
            'x1': -params.abutment_width - 2,
            'y1': params.hfl,
            'x2': deck_end + params.abutment_width + 2,
            'y2': params.hfl,
            'layer': 'WATER_LEVEL',
            'label': f'HFL {params.hfl:.2f}m'
        }
        entities.append(hfl_line)
        
        # Bed level
        bed_line = {
            'type': 'LINE',
            'x1': -params.abutment_width - 2,
            'y1': params.bed_level,
            'x2': deck_end + params.abutment_width + 2,
            'y2': params.bed_level,
            'layer': 'GROUND',
            'label': f'BED {params.bed_level:.2f}m'
        }
        entities.append(bed_line)
        
        return {
            'title': 'GENERAL ARRANGEMENT DRAWING - ELEVATION',
            'entities': entities,
            'layers': ['ABUTMENTS', 'PIERS', 'DECK', 'WATER_LEVEL', 'GROUND', 'DIMENSIONS'],
            'scale': '1:100'
        }
    
    @staticmethod
    def create_pier_details(params: DrawingParameters) -> Dict:
        """
        Generate Pier Details Drawing.
        Common elements: elevation, cross-section, reinforcement, dimensions.
        """
        entities = []
        
        # Pier elevation
        pier_elevation = {
            'type': 'RECTANGLE',
            'x': -params.pier_width/2,
            'y': params.foundation_level,
            'width': params.pier_width,
            'height': params.pier_depth,
            'layer': 'PIERS'
        }
        entities.append(pier_elevation)
        
        # Pier cap
        pier_cap = {
            'type': 'RECTANGLE',
            'x': -params.pier_cap_width/2,
            'y': params.rtl - params.pier_cap_height,
            'width': params.pier_cap_width,
            'height': params.pier_cap_height,
            'layer': 'PIERS'
        }
        entities.append(pier_cap)
        
        # Cross-section A-A
        cross_section = {
            'type': 'RECTANGLE',
            'x': params.pier_width + 2,
            'y': params.foundation_level,
            'width': params.pier_width,
            'height': params.pier_depth,
            'layer': 'PIERS',
            'section_label': 'A-A'
        }
        entities.append(cross_section)
        
        # Main reinforcement bars
        num_bars = 8
        for i in range(num_bars):
            angle = (i / num_bars) * 360
            bar = {
                'type': 'CIRCLE',
                'center_x': params.pier_width + 2,
                'center_y': params.foundation_level + params.pier_depth/2,
                'radius': 0.016,  # 16mm bar
                'layer': 'REBAR',
                'label': f'{num_bars}-T16'
            }
            entities.append(bar)
        
        return {
            'title': 'PIER DETAILS - ELEVATION & CROSS-SECTION',
            'entities': entities,
            'layers': ['PIERS', 'REBAR', 'DIMENSIONS', 'ANNOTATIONS'],
            'scale': '1:50'
        }
    
    @staticmethod
    def create_abutment_details(params: DrawingParameters) -> Dict:
        """
        Generate Abutment Details Drawing.
        Common elements: elevation, plan, wing walls, reinforcement.
        """
        entities = []
        
        # Abutment stem
        stem = {
            'type': 'RECTANGLE',
            'x': 0,
            'y': params.foundation_level,
            'width': params.abutment_width,
            'height': params.abutment_height,
            'layer': 'ABUTMENTS'
        }
        entities.append(stem)
        
        # Base slab
        base = {
            'type': 'RECTANGLE',
            'x': -0.5,
            'y': params.foundation_level - 0.3,
            'width': params.abutment_base_width + 0.5,
            'height': 0.3,
            'layer': 'ABUTMENTS'
        }
        entities.append(base)
        
        # Wing walls
        wing_wall_left = {
            'type': 'POLYLINE',
            'points': [
                (0, params.foundation_level),
                (-2, params.foundation_level - 1),
                (-2, params.foundation_level - 2),
                (0, params.foundation_level - 1.5)
            ],
            'layer': 'ABUTMENTS',
            'label': 'WING WALL'
        }
        entities.append(wing_wall_left)
        
        # Dirt wall
        dirt_wall = {
            'type': 'RECTANGLE',
            'x': params.abutment_width,
            'y': params.rtl - 0.5,
            'width': 0.3,
            'height': 0.5,
            'layer': 'ABUTMENTS'
        }
        entities.append(dirt_wall)
        
        return {
            'title': 'ABUTMENT DETAILS - ELEVATION & PLAN',
            'entities': entities,
            'layers': ['ABUTMENTS', 'REBAR', 'DIMENSIONS', 'ANNOTATIONS'],
            'scale': '1:50'
        }
    
    @staticmethod
    def create_deck_slab_reinforcement(params: DrawingParameters) -> Dict:
        """
        Generate Deck Slab Reinforcement Drawing.
        Common elements: top/bottom mesh, extra bars, dimensions.
        """
        entities = []
        
        # Slab outline
        slab = {
            'type': 'RECTANGLE',
            'x': 0,
            'y': 0,
            'width': params.carriage_width,
            'height': params.span_length,
            'layer': 'DECK'
        }
        entities.append(slab)
        
        # Top reinforcement (transverse)
        for i in range(int(params.span_length / 0.15)):
            bar = {
                'type': 'LINE',
                'x1': 0.05,
                'y1': i * 0.15,
                'x2': params.carriage_width - 0.05,
                'y2': i * 0.15,
                'layer': 'REBAR_TOP',
                'label': 'T12 @ 150mm c/c'
            }
            entities.append(bar)
        
        # Bottom reinforcement (longitudinal)
        for i in range(int(params.carriage_width / 0.15)):
            bar = {
                'type': 'LINE',
                'x1': i * 0.15,
                'y1': 0.05,
                'x2': i * 0.15,
                'y2': params.span_length - 0.05,
                'layer': 'REBAR_BOTTOM',
                'label': 'T12 @ 150mm c/c'
            }
            entities.append(bar)
        
        return {
            'title': 'DECK SLAB REINFORCEMENT DETAILS',
            'entities': entities,
            'layers': ['DECK', 'REBAR_TOP', 'REBAR_BOTTOM', 'DIMENSIONS'],
            'scale': '1:20'
        }
    
    @staticmethod
    def create_cross_section(params: DrawingParameters) -> Dict:
        """
        Generate Typical Cross Section Drawing.
        Common elements: carriageway, footpath, kerb, slab, girders.
        """
        entities = []
        
        total_width = params.carriage_width + 2 * params.footpath_width
        
        # Deck slab
        deck = {
            'type': 'RECTANGLE',
            'x': -total_width/2,
            'y': params.rtl - params.slab_thickness,
            'width': total_width,
            'height': params.slab_thickness,
            'layer': 'DECK'
        }
        entities.append(deck)
        
        # Wearing coat
        wearing = {
            'type': 'RECTANGLE',
            'x': -total_width/2,
            'y': params.rtl,
            'width': total_width,
            'height': params.wearing_coat_thickness,
            'layer': 'WEARING_COAT'
        }
        entities.append(wearing)
        
        # Kerbs
        for side in [-1, 1]:
            kerb = {
                'type': 'RECTANGLE',
                'x': side * (params.carriage_width/2),
                'y': params.rtl - params.slab_thickness - 0.3,
                'width': 0.3,
                'height': 0.3,
                'layer': 'KERB'
            }
            entities.append(kerb)
        
        # Footpaths
        for side in [-1, 1]:
            footpath = {
                'type': 'RECTANGLE',
                'x': side * (params.carriage_width/2 + params.footpath_width/2 + 0.15),
                'y': params.rtl - params.slab_thickness,
                'width': params.footpath_width,
                'height': params.slab_thickness,
                'layer': 'FOOTPATH'
            }
            entities.append(footpath)
        
        return {
            'title': 'TYPICAL CROSS SECTION',
            'entities': entities,
            'layers': ['DECK', 'WEARING_COAT', 'KERB', 'FOOTPATH', 'DIMENSIONS'],
            'scale': '1:20'
        }
    
    @staticmethod
    def create_wing_wall_details(params: DrawingParameters) -> Dict:
        """
        Generate Wing Wall Details Drawing.
        Common elements: elevation, plan, section, reinforcement.
        Based on: WING WALL SKIN REINF DESIGN.dwg patterns
        """
        entities = []
        
        # Wing wall elevation (return type)
        wing_wall_elev = {
            'type': 'POLYLINE',
            'points': [
                (0, 0),
                (params.wing_wall_length, -params.wing_wall_length * 0.3),
                (params.wing_wall_length, params.wing_wall_height),
                (0, params.wing_wall_height + 0.5),
                (0, 0)
            ],
            'layer': 'WING_WALL',
            'label': 'WING WALL ELEVATION'
        }
        entities.append(wing_wall_elev)
        
        # Wing wall plan view
        wing_wall_plan = {
            'type': 'POLYLINE',
            'points': [
                (0, 0),
                (params.wing_wall_length * 0.8, 0),
                (params.wing_wall_length, 2.0),
                (0, 2.0),
                (0, 0)
            ],
            'layer': 'WING_WALL',
            'label': 'WING WALL PLAN'
        }
        entities.append(wing_wall_plan)
        
        # Horizontal reinforcement
        num_h_bars = int(params.wing_wall_height / 0.2)
        for i in range(num_h_bars):
            bar = {
                'type': 'LINE',
                'x1': 0.05,
                'y1': i * 0.2 + 0.1,
                'x2': params.wing_wall_length - 0.05,
                'y2': i * 0.2 + 0.1,
                'layer': 'REBAR_HORIZONTAL',
                'label': 'T12 @ 200mm c/c'
            }
            entities.append(bar)
        
        # Vertical reinforcement
        num_v_bars = int(params.wing_wall_length / 0.2)
        for i in range(num_v_bars):
            bar = {
                'type': 'LINE',
                'x1': i * 0.2 + 0.1,
                'y1': 0.05,
                'x2': i * 0.2 + 0.1,
                'y2': params.wing_wall_height - 0.05,
                'layer': 'REBAR_VERTICAL',
                'label': 'T12 @ 200mm c/c'
            }
            entities.append(bar)
        
        # Weep holes
        for i in range(2):
            weep_hole = {
                'type': 'CIRCLE',
                'center_x': params.wing_wall_length * 0.5,
                'center_y': 1.0 + i * 1.5,
                'radius': 0.05,
                'layer': 'WEEP_HOLES',
                'label': '100mm φ WEEP HOLE'
            }
            entities.append(weep_hole)
        
        return {
            'title': 'WING WALL DETAILS - ELEVATION, PLAN & REINFORCEMENT',
            'entities': entities,
            'layers': ['WING_WALL', 'REBAR_HORIZONTAL', 'REBAR_VERTICAL', 'WEEP_HOLES', 'DIMENSIONS'],
            'scale': '1:50'
        }
    
    @staticmethod
    def create_bed_protection_details(params: DrawingParameters) -> Dict:
        """
        Generate Bed Protection Details Drawing.
        Common elements: bed anchorage, protection slab, cutoff walls.
        Based on: BED PROTECTION.dwg, BED ANCHORAGE DETAILS.dwg patterns
        """
        entities = []
        
        # Bed protection slab
        protection_slab = {
            'type': 'RECTANGLE',
            'x': -params.bed_protection_length,
            'y': params.bed_level - params.bed_protection_thickness,
            'width': params.bed_protection_length * 2,
            'height': params.bed_protection_thickness,
            'layer': 'BED_PROTECTION',
            'label': 'BED PROTECTION SLAB'
        }
        entities.append(protection_slab)
        
        # Cutoff wall upstream
        cutoff_upstream = {
            'type': 'RECTANGLE',
            'x': -params.bed_protection_length,
            'y': params.bed_level - params.bed_protection_thickness - 1.5,
            'width': 0.3,
            'height': 1.5,
            'layer': 'CUTOFF_WALL',
            'label': 'CUTOFF WALL'
        }
        entities.append(cutoff_upstream)
        
        # Cutoff wall downstream
        cutoff_downstream = {
            'type': 'RECTANGLE',
            'x': params.bed_protection_length - 0.3,
            'y': params.bed_level - params.bed_protection_thickness - 1.5,
            'width': 0.3,
            'height': 1.5,
            'layer': 'CUTOFF_WALL',
            'label': 'CUTOFF WALL'
        }
        entities.append(cutoff_downstream)
        
        # Anchorage bars
        num_anchors = int(params.bed_protection_length * 2 / 1.0)
        for i in range(num_anchors):
            anchor = {
                'type': 'LINE',
                'x1': -params.bed_protection_length + i * 1.0 + 0.5,
                'y1': params.bed_level - params.bed_protection_thickness,
                'x2': -params.bed_protection_length + i * 1.0 + 0.5,
                'y2': params.bed_level - params.bed_protection_thickness - 0.8,
                'layer': 'ANCHORAGE',
                'label': 'T16 ANCHORAGE @ 1000mm c/c'
            }
            entities.append(anchor)
        
        # River bed line
        bed_line = {
            'type': 'LINE',
            'x1': -params.bed_protection_length - 2,
            'y1': params.bed_level,
            'x2': params.bed_protection_length + 2,
            'y2': params.bed_level,
            'layer': 'GROUND',
            'label': f'BED LEVEL {params.bed_level:.2f}m'
        }
        entities.append(bed_line)
        
        return {
            'title': 'BED PROTECTION & ANCHORAGE DETAILS',
            'entities': entities,
            'layers': ['BED_PROTECTION', 'CUTOFF_WALL', 'ANCHORAGE', 'GROUND', 'DIMENSIONS'],
            'scale': '1:50'
        }
    
    @staticmethod
    def create_deck_slab_anchorage(params: DrawingParameters) -> Dict:
        """
        Generate Deck Slab Anchorage Details.
        Common elements: anchorage bars, bearing pads, expansion joints.
        Based on: DECK SLAB ANCHORAGE.dwg patterns
        """
        entities = []
        
        # Slab edge
        slab_edge = {
            'type': 'RECTANGLE',
            'x': 0,
            'y': 0,
            'width': 0.5,
            'height': params.slab_thickness,
            'layer': 'DECK',
            'label': 'SLAB EDGE'
        }
        entities.append(slab_edge)
        
        # Anchorage bars (horizontal)
        for i in range(4):
            anchor_bar = {
                'type': 'LINE',
                'x1': 0.05,
                'y1': i * (params.slab_thickness / 4) + params.slab_thickness / 8,
                'x2': 0.45,
                'y2': i * (params.slab_thickness / 4) + params.slab_thickness / 8,
                'layer': 'ANCHORAGE_REBAR',
                'label': 'T12 ANCHORAGE BAR'
            }
            entities.append(anchor_bar)
        
        # Vertical dowel bars
        for i in range(3):
            dowel = {
                'type': 'LINE',
                'x1': i * 0.15 + 0.1,
                'y1': -0.3,
                'x2': i * 0.15 + 0.1,
                'y2': params.slab_thickness,
                'layer': 'DOWEL_BARS',
                'label': 'T16 DOWEL @ 150mm c/c'
            }
            entities.append(dowel)
        
        # Bearing pad
        bearing_pad = {
            'type': 'RECTANGLE',
            'x': 0.1,
            'y': -0.05,
            'width': 0.3,
            'height': 0.05,
            'layer': 'BEARING',
            'label': 'ELASTOMERIC BEARING'
        }
        entities.append(bearing_pad)
        
        return {
            'title': 'DECK SLAB ANCHORAGE DETAILS',
            'entities': entities,
            'layers': ['DECK', 'ANCHORAGE_REBAR', 'DOWEL_BARS', 'BEARING', 'DIMENSIONS'],
            'scale': '1:20'
        }
    
    @staticmethod
    def create_guard_stone_details(params: DrawingParameters) -> Dict:
        """
        Generate Guard Stone & Kerb Details.
        Common elements: guard stone, kerb, railing posts.
        Based on: GUARD STONE DETAILS.dwg patterns
        """
        entities = []
        
        # Kerb
        kerb = {
            'type': 'RECTANGLE',
            'x': 0,
            'y': 0,
            'width': 0.3,
            'height': 0.3,
            'layer': 'KERB',
            'label': 'KERB 300x300mm'
        }
        entities.append(kerb)
        
        # Guard stone
        guard_stone = {
            'type': 'RECTANGLE',
            'x': 0.05,
            'y': 0.3,
            'width': 0.2,
            'height': 1.0,
            'layer': 'GUARD_STONE',
            'label': 'GUARD STONE'
        }
        entities.append(guard_stone)
        
        # Railing posts
        for i in range(3):
            post = {
                'type': 'RECTANGLE',
                'x': i * 1.5 + 0.1,
                'y': 0.3,
                'width': 0.05,
                'height': 1.2,
                'layer': 'RAILING',
                'label': 'RAILING POST'
            }
            entities.append(post)
        
        # Top rail
        top_rail = {
            'type': 'LINE',
            'x1': 0.125,
            'y1': 1.5,
            'x2': 3.125,
            'y2': 1.5,
            'layer': 'RAILING',
            'label': 'TOP RAIL'
        }
        entities.append(top_rail)
        
        # Middle rail
        middle_rail = {
            'type': 'LINE',
            'x1': 0.125,
            'y1': 1.0,
            'x2': 3.125,
            'y2': 1.0,
            'layer': 'RAILING',
            'label': 'MIDDLE RAIL'
        }
        entities.append(middle_rail)
        
        return {
            'title': 'GUARD STONE & KERB DETAILS',
            'entities': entities,
            'layers': ['KERB', 'GUARD_STONE', 'RAILING', 'DIMENSIONS'],
            'scale': '1:20'
        }
    
    @staticmethod
    def create_expansion_joint_details(params: DrawingParameters) -> Dict:
        """
        Generate Expansion Joint Details.
        Common elements: joint gap, filler, sealant, armor.
        Based on: ENDJOINT.dwg patterns
        """
        entities = []
        
        # Gap between slabs
        gap = {
            'type': 'RECTANGLE',
            'x': -0.02,
            'y': 0,
            'width': 0.04,
            'height': params.slab_thickness,
            'layer': 'EXPANSION_JOINT',
            'label': '40mm EXPANSION JOINT'
        }
        entities.append(gap)
        
        # Filler material
        filler = {
            'type': 'RECTANGLE',
            'x': -0.015,
            'y': 0.05,
            'width': 0.03,
            'height': params.slab_thickness - 0.1,
            'layer': 'FILLER',
            'label': 'FILLER BOARD'
        }
        entities.append(filler)
        
        # Sealant at top
        sealant = {
            'type': 'RECTANGLE',
            'x': -0.02,
            'y': params.slab_thickness - 0.02,
            'width': 0.04,
            'height': 0.02,
            'layer': 'SEALANT',
            'label': 'POLYSULPHIDE SEALANT'
        }
        entities.append(sealant)
        
        # Armor angle (both sides)
        for side in [-1, 1]:
            armor = {
                'type': 'POLYLINE',
                'points': [
                    (side * 0.02, params.slab_thickness),
                    (side * 0.06, params.slab_thickness),
                    (side * 0.06, params.slab_thickness - 0.05),
                    (side * 0.02, params.slab_thickness - 0.05)
                ],
                'layer': 'ARMOR',
                'label': 'ISA 60x60x6 ANGLE'
            }
            entities.append(armor)
        
        return {
            'title': 'EXPANSION JOINT DETAILS',
            'entities': entities,
            'layers': ['EXPANSION_JOINT', 'FILLER', 'SEALANT', 'ARMOR', 'DIMENSIONS'],
            'scale': '1:10'
        }
    
    @staticmethod
    def create_bearing_details(params: DrawingParameters) -> Dict:
        """
        Generate Bearing Details Drawing.
        Common elements: elastomeric pad, steel plates, pedestals.
        """
        entities = []
        
        # Elastomeric bearing pad
        bearing_pad = {
            'type': 'RECTANGLE',
            'x': -0.2,
            'y': 0,
            'width': 0.4,
            'height': 0.05,
            'layer': 'BEARING',
            'label': 'ELASTOMERIC BEARING 400x250x50mm'
        }
        entities.append(bearing_pad)
        
        # Steel reinforcement plates
        for i in range(3):
            steel_plate = {
                'type': 'RECTANGLE',
                'x': -0.19,
                'y': 0.01 + i * 0.015,
                'width': 0.38,
                'height': 0.003,
                'layer': 'STEEL_PLATES',
                'label': '3mm STEEL PLATE'
            }
            entities.append(steel_plate)
        
        # Bearing pedestal
        pedestal = {
            'type': 'RECTANGLE',
            'x': -0.25,
            'y': -0.3,
            'width': 0.5,
            'height': 0.3,
            'layer': 'PEDESTAL',
            'label': f'BEARING PEDESTAL ({params.concrete_grade})'
        }
        entities.append(pedestal)
        
        # Anchor bolts
        for x_pos in [-0.15, 0.15]:
            for y_pos in [-0.25, -0.05]:
                bolt = {
                    'type': 'CIRCLE',
                    'center_x': x_pos,
                    'center_y': y_pos,
                    'radius': 0.012,
                    'layer': 'ANCHOR_BOLTS',
                    'label': '24mm φ ANCHOR BOLT'
                }
                entities.append(bolt)
        
        return {
            'title': 'BEARING DETAILS - ELASTOMERIC PAD & PEDESTAL',
            'entities': entities,
            'layers': ['BEARING', 'STEEL_PLATES', 'PEDESTAL', 'ANCHOR_BOLTS', 'DIMENSIONS'],
            'scale': '1:10'
        }
    
    @staticmethod
    def create_foundation_details(params: DrawingParameters) -> Dict:
        """
        Generate Foundation Details Drawing.
        Common elements: open foundation (footing) or pile foundation.
        """
        entities = []
        
        # Well foundation / Footing
        footing = {
            'type': 'RECTANGLE',
            'x': -params.footing_width / 2,
            'y': params.foundation_level - params.footing_depth,
            'width': params.footing_width,
            'height': params.footing_depth,
            'layer': 'FOUNDATION',
            'label': f'OPEN FOUNDATION {params.footing_width:.1f}m x {params.footing_width:.1f}m'
        }
        entities.append(footing)
        
        # Pile foundation (alternative)
        if params.number_of_piles > 0:
            pile_cap = {
                'type': 'RECTANGLE',
                'x': -1.5,
                'y': params.foundation_level - 0.8,
                'width': 3.0,
                'height': 0.8,
                'layer': 'PILE_CAP',
                'label': 'PILE CAP'
            }
            entities.append(pile_cap)
            
            # Piles
            for i in range(params.number_of_piles):
                x_offset = (i - params.number_of_piles / 2 + 0.5) * 0.8
                pile = {
                    'type': 'RECTANGLE',
                    'x': x_offset - params.pile_diameter / 2,
                    'y': params.foundation_level - params.footing_depth - params.pile_length,
                    'width': params.pile_diameter,
                    'height': params.pile_length,
                    'layer': 'PILES',
                    'label': f'PILE {params.pile_diameter:.1f}m φ x {params.pile_length:.1f}m'
                }
                entities.append(pile)
        
        # Foundation reinforcement
        num_bars = int(params.footing_width / 0.15)
        for i in range(num_bars):
            bar = {
                'type': 'LINE',
                'x1': -params.footing_width / 2 + 0.05,
                'y1': params.foundation_level - params.footing_depth + 0.05 + i * 0.15,
                'x2': params.footing_width / 2 - 0.05,
                'y2': params.foundation_level - params.footing_depth + 0.05 + i * 0.15,
                'layer': 'REBAR',
                'label': 'T16 @ 150mm c/c'
            }
            entities.append(bar)
        
        return {
            'title': 'FOUNDATION DETAILS - FOOTING / PILE FOUNDATION',
            'entities': entities,
            'layers': ['FOUNDATION', 'PILE_CAP', 'PILES', 'REBAR', 'DIMENSIONS'],
            'scale': '1:50'
        }
    
    @staticmethod
    def create_false_work_details(params: DrawingParameters) -> Dict:
        """
        Generate False Work / Formwork Details.
        Common elements: scaffolding, props, beams, plates.
        Based on: BRITRUDA1.dxf, ENDJOINT.dxf patterns
        """
        entities = []
        
        # Main beam
        main_beam = {
            'type': 'RECTANGLE',
            'x': 0,
            'y': params.rtl - 0.5,
            'width': params.span_length,
            'height': 0.5,
            'layer': 'BEAM',
            'label': 'MAIN BEAM'
        }
        entities.append(main_beam)
        
        # Support props
        num_props = int(params.span_length / 2) + 1
        for i in range(num_props):
            prop = {
                'type': 'RECTANGLE',
                'x': i * 2 - 0.1,
                'y': params.foundation_level,
                'width': 0.2,
                'height': params.rtl - 0.5 - params.foundation_level,
                'layer': 'PROPS',
                'label': f'STEEL PROP {i+1}'
            }
            entities.append(prop)
        
        # Cross bracing
        for i in range(num_props - 1):
            brace = {
                'type': 'LINE',
                'x1': i * 2,
                'y1': params.foundation_level + 2,
                'x2': (i + 1) * 2,
                'y2': params.foundation_level + 3,
                'layer': 'BRACING',
                'label': 'CROSS BRACING'
            }
            entities.append(brace)
        
        # Formwork plates
        for i in range(int(params.span_length / 1.0)):
            plate = {
                'type': 'RECTANGLE',
                'x': i * 1.0,
                'y': params.rtl - 0.55,
                'width': 1.0,
                'height': 0.05,
                'layer': 'PLATE',
                'label': 'FORMWORK PLATE'
            }
            entities.append(plate)
        
        return {
            'title': 'FALSE WORK / FORMWORK DETAILS',
            'entities': entities,
            'layers': ['BEAM', 'PROPS', 'BRACING', 'PLATE', 'DIMENSIONS'],
            'scale': '1:50'
        }
    
    @staticmethod
    def create_culvert_details(params: DrawingParameters) -> Dict:
        """
        Generate Culvert Details Drawing.
        Common elements: box culvert, walls, slab, foundation.
        Based on: CULVERT drawing patterns
        """
        entities = []
        
        # Box culvert dimensions
        culvert_width = 3.0
        culvert_height = 2.5
        
        # Bottom slab
        bottom_slab = {
            'type': 'RECTANGLE',
            'x': -culvert_width / 2,
            'y': params.foundation_level,
            'width': culvert_width,
            'height': 0.25,
            'layer': 'CULVERT_SLAB',
            'label': 'BOTTOM SLAB 250mm'
        }
        entities.append(bottom_slab)
        
        # Top slab
        top_slab = {
            'type': 'RECTANGLE',
            'x': -culvert_width / 2,
            'y': params.foundation_level + culvert_height,
            'width': culvert_width,
            'height': 0.25,
            'layer': 'CULVERT_SLAB',
            'label': 'TOP SLAB 250mm'
        }
        entities.append(top_slab)
        
        # Side walls
        for side in [-1, 1]:
            wall = {
                'type': 'RECTANGLE',
                'x': side * culvert_width / 2 - 0.15,
                'y': params.foundation_level,
                'width': 0.3,
                'height': culvert_height,
                'layer': 'CULVERT_WALL',
                'label': 'SIDE WALL 300mm'
            }
            entities.append(wall)
        
        # Reinforcement in walls
        num_bars = int(culvert_height / 0.2)
        for i in range(num_bars):
            for side in [-1, 1]:
                bar = {
                    'type': 'LINE',
                    'x1': side * culvert_width / 2 - 0.1,
                    'y1': params.foundation_level + i * 0.2 + 0.1,
                    'x2': side * culvert_width / 2 + 0.1,
                    'y2': params.foundation_level + i * 0.2 + 0.1,
                    'layer': 'REBAR',
                    'label': 'T12 @ 200mm c/c'
                }
                entities.append(bar)
        
        return {
            'title': 'BOX CULVERT DETAILS',
            'entities': entities,
            'layers': ['CULVERT_SLAB', 'CULVERT_WALL', 'REBAR', 'DIMENSIONS'],
            'scale': '1:50'
        }
    
    @staticmethod
    def create_pier_reinforcement_detailed(params: DrawingParameters) -> Dict:
        """
        Generate Detailed Pier Reinforcement Drawing.
        Common elements: main bars, stirrups, tie bars, laps.
        Based on: PIER REINFORCEMENT patterns from collection
        """
        entities = []
        
        # Pier cross-section outline
        pier_outline = {
            'type': 'RECTANGLE',
            'x': -params.pier_width / 2,
            'y': -params.pier_depth / 2,
            'width': params.pier_width,
            'height': params.pier_depth,
            'layer': 'PIER_OUTLINE',
            'label': f'PIER {params.pier_width:.1f}m x {params.pier_depth:.1f}m'
        }
        entities.append(pier_outline)
        
        # Main longitudinal bars
        num_main_bars = 12
        for i in range(num_main_bars):
            if i < 4:  # Corner and side bars
                x = -params.pier_width / 2 + 0.05 + (i % 4) * (params.pier_width - 0.1) / 3
                y = -params.pier_depth / 2 + 0.05 if i < 2 else params.pier_depth / 2 - 0.05
            else:
                side = (i - 4) % 2
                idx = (i - 4) // 2
                x = -params.pier_width / 2 + 0.05 if side == 0 else params.pier_width / 2 - 0.05
                y = -params.pier_depth / 2 + 0.05 + idx * (params.pier_depth - 0.1)
            
            bar = {
                'type': 'CIRCLE',
                'center_x': x,
                'center_y': y,
                'radius': 0.016,
                'layer': 'MAIN_REBAR',
                'label': 'T16'
            }
            entities.append(bar)
        
        # Lateral ties (stirrups)
        tie_spacing = 0.2
        num_ties = int(params.pier_depth / tie_spacing)
        for i in range(num_ties):
            y_pos = -params.pier_depth / 2 + 0.05 + i * tie_spacing
            tie = {
                'type': 'RECTANGLE',
                'x': -params.pier_width / 2 + 0.05,
                'y': y_pos,
                'width': params.pier_width - 0.1,
                'height': 0.01,
                'layer': 'TIES',
                'label': 'T10 @ 200mm c/c'
            }
            entities.append(tie)
        
        return {
            'title': 'PIER REINFORCEMENT DETAILS - CROSS SECTION',
            'entities': entities,
            'layers': ['PIER_OUTLINE', 'MAIN_REBAR', 'TIES', 'DIMENSIONS'],
            'scale': '1:20'
        }


# Example usage
if __name__ == "__main__":
    # Create standard parameters for a typical submersible bridge
    params = DrawingParameters(
        span_length=14.0,
        number_of_spans=3,
        carriage_width=7.5,
        footpath_width=1.5,
        rtl=100.500,
        hfl=98.200,
        bed_level=95.000,
        foundation_level=90.000,
        agl=96.500,
        pier_width=1.2,
        pier_depth=8.0,
        pier_cap_height=0.5,
        pier_cap_width=2.0,
        abutment_width=1.5,
        abutment_base_width=3.0,
        abutment_height=6.0,
        slab_thickness=0.45,
        wearing_coat_thickness=0.075,
        skew_angle=30.0,  # 30 degree skew
        project_name="Sample Submersible Bridge",
        drawing_no="GAD-001",
        bridge_type=BridgeType.SUBMERSIBLE_BRIDGE,
        pier_type=PierType.SOLID_RECTANGULAR,
        abutment_type=AbutmentType.CANTILEVER,
        wing_wall_length=3.0,
        wing_wall_angle=45.0,
        bed_protection_length=5.0,
        footing_width=4.0,
        pile_diameter=0.6,
        pile_length=12.0,
        number_of_piles=4
    )
    
    # Generate all drawing forms
    forms = CommonDrawingForms()
    
    drawing_forms = [
        ("GAD Elevation", forms.create_gad_elevation(params)),
        ("Pier Details", forms.create_pier_details(params)),
        ("Abutment Details", forms.create_abutment_details(params)),
        ("Deck Slab Reinforcement", forms.create_deck_slab_reinforcement(params)),
        ("Cross Section", forms.create_cross_section(params)),
        ("Wing Wall Details", forms.create_wing_wall_details(params)),
        ("Bed Protection", forms.create_bed_protection_details(params)),
        ("Deck Slab Anchorage", forms.create_deck_slab_anchorage(params)),
        ("Guard Stone Details", forms.create_guard_stone_details(params)),
        ("Expansion Joint", forms.create_expansion_joint_details(params)),
        ("Bearing Details", forms.create_bearing_details(params)),
        ("Foundation Details", forms.create_foundation_details(params)),
        ("False Work", forms.create_false_work_details(params)),
        ("Culvert Details", forms.create_culvert_details(params)),
        ("Pier Reinforcement", forms.create_pier_reinforcement_detailed(params)),
    ]
    
    print("=" * 80)
    print("COMMON DRAWING FORMS GENERATOR")
    print("=" * 80)
    print(f"\nProject: {params.project_name}")
    print(f"Bridge Type: {params.bridge_type.value}")
    print(f"Span: {params.number_of_spans} x {params.span_length}m = {params.number_of_spans * params.span_length}m")
    print(f"Skew Angle: {params.skew_angle}°")
    print(f"Concrete: {params.concrete_grade}, Steel: {params.steel_grade}")
    print("\n" + "=" * 80)
    
    for name, drawing in drawing_forms:
        print(f"\n{name}:")
        print(f"  Title: {drawing['title']}")
        print(f"  Entities: {len(drawing['entities'])}")
        print(f"  Layers: {', '.join(drawing['layers'])}")
        print(f"  Scale: {drawing['scale']}")
    
    print("\n" + "=" * 80)
    print(f"✅ Generated {len(drawing_forms)} common drawing forms successfully!")
    print("=" * 80)
    print("\nDrawing Forms Summary:")
    print("  1.  General Arrangement Drawing (GAD)")
    print("  2.  Pier Details (Geometry & Elevation)")
    print("  3.  Abutment Details (Cantilever Type)")
    print("  4.  Deck Slab Reinforcement")
    print("  5.  Typical Cross Section")
    print("  6.  Wing Wall Details")
    print("  7.  Bed Protection & Anchorage")
    print("  8.  Deck Slab Anchorage")
    print("  9.  Guard Stone & Kerb Details")
    print("  10. Expansion Joint Details")
    print("  11. Bearing Details (Elastomeric)")
    print("  12. Foundation Details (Open/Pile)")
    print("  13. False Work / Formwork")
    print("  14. Box Culvert Details")
    print("  15. Pier Reinforcement (Detailed)")
    print("\nAll forms are parameterized and ready for DXF export!")
