"""
DXF File Generator for Common Drawing Forms
Converts drawing form definitions into actual DXF files.

Author: Auto-generated by DXF Pattern Analyzer
Date: 2026-04-18
"""

import math
from typing import Dict, List, Tuple
from pathlib import Path


class DXFGenerator:
    """Generates DXF files from drawing form definitions."""
    
    def __init__(self):
        self.entities = []
        self.layers = set()
    
    def _add_layer(self, layer_name: str, color: int = 7):
        """Add a layer definition."""
        self.layers.add((layer_name, color))
    
    def _entity_header(self, layer: str) -> str:
        """Create entity header with layer."""
        return f"  8\n{layer}\n"
    
    def line(self, x1: float, y1: float, x2: float, y2: float, layer: str) -> str:
        """Create a LINE entity."""
        self._add_layer(layer)
        return (
            f"  0\nLINE\n"
            f"{self._entity_header(layer)}"
            f" 10\n{x1:.4f}\n 20\n{y1:.4f}\n 30\n0.0\n"
            f" 11\n{x2:.4f}\n 21\n{y2:.4f}\n 31\n0.0\n"
        )
    
    def circle(self, cx: float, cy: float, r: float, layer: str) -> str:
        """Create a CIRCLE entity."""
        self._add_layer(layer)
        return (
            f"  0\nCIRCLE\n"
            f"{self._entity_header(layer)}"
            f" 10\n{cx:.4f}\n 20\n{cy:.4f}\n 30\n0.0\n"
            f" 40\n{r:.4f}\n"
        )
    
    def text(self, x: float, y: float, text: str, height: float, layer: str) -> str:
        """Create a TEXT entity."""
        self._add_layer(layer)
        return (
            f"  0\nTEXT\n"
            f"{self._entity_header(layer)}"
            f" 10\n{x:.4f}\n 20\n{y:.4f}\n 30\n0.0\n"
            f" 40\n{height:.4f}\n"
            f"  1\n{text}\n"
            f" 72\n1\n"
            f" 11\n{x:.4f}\n 21\n{y:.4f}\n 31\n0.0\n"
        )
    
    def polyline(self, points: List[Tuple[float, float]], layer: str, closed: bool = False) -> str:
        """Create a LWPOLYLINE entity."""
        self._add_layer(layer)
        flag = 1 if closed else 0
        entity = (
            f"  0\nLWPOLYLINE\n"
            f"{self._entity_header(layer)}"
            f" 90\n{len(points)}\n"
            f" 70\n{flag}\n"
        )
        for x, y in points:
            entity += f" 10\n{x:.4f}\n 20\n{y:.4f}\n"
        return entity
    
    def rectangle(self, x: float, y: float, width: float, height: float, layer: str) -> str:
        """Create a rectangle using LWPOLYLINE."""
        points = [
            (x, y),
            (x + width, y),
            (x + width, y + height),
            (x, y + height)
        ]
        return self.polyline(points, layer, closed=True)
    
    def dashed_line(self, x1: float, y1: float, x2: float, y2: float, 
                   layer: str, segment_length: float = 0.5) -> str:
        """Create a dashed line using multiple line segments."""
        self._add_layer(layer)
        length = math.sqrt((x2-x1)**2 + (y2-y1)**2)
        segments = int(length / segment_length)
        
        entities = ""
        for i in range(0, segments, 2):
            t1 = i / segments
            t2 = (i + 1) / segments
            sx1 = x1 + (x2 - x1) * t1
            sy1 = y1 + (y2 - y1) * t1
            sx2 = x1 + (x2 - x1) * t2
            sy2 = y1 + (y2 - y1) * t2
            entities += self.line(sx1, sy1, sx2, sy2, layer)
        
        return entities
    
    def dimension_line(self, x1: float, y1: float, x2: float, y2: float, 
                      offset: float, layer: str, label: str) -> str:
        """Create dimension lines with text."""
        entities = ""
        
        # Extension lines
        entities += self.line(x1, y1, x1, y1 + offset, layer)
        entities += self.line(x2, y2, x2, y2 + offset, layer)
        
        # Dimension line
        entities += self.line(x1, y1 + offset, x2, y2 + offset, layer)
        
        # Dimension text
        mid_x = (x1 + x2) / 2
        mid_y = y1 + offset
        entities += self.text(mid_x, mid_y + 0.2, label, 0.3, layer)
        
        return entities
    
    def create_header_section(self) -> str:
        """Create DXF HEADER section."""
        return """  0
SECTION
  2
HEADER
  9
$ACADVER
  1
AC1018
  9
$EXTMIN
 10
-100.0
 20
-100.0
 30
0.0
  9
$EXTMAX
 10
1000.0
 20
1000.0
 30
0.0
  0
ENDSEC
"""
    
    def create_tables_section(self) -> str:
        """Create DXF TABLES section with layer definitions."""
        tables = "  0\nSECTION\n  2\nTABLES\n"
        
        # LTYPE table
        tables += """  0
TABLE
  2
LTYPE
 70
2
  0
LTYPE
  2
CONTINUOUS
 70
0
 40
1.0
  3
Solid line
 72
65
 73
0
  0
LTYPE
  2
DASHED
 70
0
 40
1.0
  3
Dashed line
 72
65
 73
2
 40
0.5
 40
-0.5
"""
        tables += "  0\nENDTAB\n"
        
        # LAYER table
        tables += "  0\nTABLE\n  2\nLAYER\n 70\n{}\n".format(len(self.layers))
        
        default_colors = {
            'ABUTMENTS': 4,
            'PIERS': 3,
            'DECK': 5,
            'WATER_LEVEL': 140,
            'GROUND': 52,
            'DIMENSIONS': 2,
            'REBAR': 1,
            'REBAR_TOP': 1,
            'REBAR_BOTTOM': 1,
            'WEARING_COAT': 8,
            'KERB': 6,
            'FOOTPATH': 7,
            'ANNOTATIONS': 2,
            'TITLEBLOCK': 6
        }
        
        for layer_name, color in self.layers:
            actual_color = default_colors.get(layer_name, color)
            tables += f"""  0
LAYER
  2
{layer_name}
 70
0
 62
{actual_color}
  6
CONTINUOUS
"""
        
        tables += "  0\nENDTAB\n"
        tables += "  0\nENDSEC\n"
        
        return tables
    
    def create_blocks_section(self) -> str:
        """Create DXF BLOCKS section (empty)."""
        return """  0
SECTION
  2
BLOCKS
  0
ENDSEC
"""
    
    def create_entities_section(self, entities: List[str]) -> str:
        """Create DXF ENTITIES section."""
        section = "  0\nSECTION\n  2\nENTITIES\n"
        for entity in entities:
            section += entity
        section += "  0\nENDSEC\n"
        return section
    
    def generate_dxf(self, drawing_form: Dict) -> str:
        """Generate complete DXF file from drawing form."""
        self.entities = []
        self.layers = set()
        
        # Process entities from drawing form
        for entity in drawing_form['entities']:
            entity_type = entity.get('type')
            
            if entity_type == 'LINE':
                self.entities.append(
                    self.line(
                        entity['x1'], entity['y1'],
                        entity['x2'], entity['y2'],
                        entity['layer']
                    )
                )
            
            elif entity_type == 'DASHED_LINE':
                self.entities.append(
                    self.dashed_line(
                        entity['x1'], entity['y1'],
                        entity['x2'], entity['y2'],
                        entity['layer']
                    )
                )
                
                # Add label if present
                if 'label' in entity:
                    mid_x = (entity['x1'] + entity['x2']) / 2
                    mid_y = (entity['y1'] + entity['y2']) / 2
                    self.entities.append(
                        self.text(mid_x - 2, mid_y, entity['label'], 0.3, entity['layer'])
                    )
            
            elif entity_type == 'RECTANGLE':
                self.entities.append(
                    self.rectangle(
                        entity['x'], entity['y'],
                        entity['width'], entity['height'],
                        entity['layer']
                    )
                )
            
            elif entity_type == 'CIRCLE':
                self.entities.append(
                    self.circle(
                        entity.get('center_x', entity.get('x', 0)),
                        entity.get('center_y', entity.get('y', 0)),
                        entity['radius'],
                        entity['layer']
                    )
                )
            
            elif entity_type == 'POLYLINE':
                self.entities.append(
                    self.polyline(
                        entity['points'],
                        entity['layer'],
                        closed=True
                    )
                )
        
        # Add title
        self.entities.append(
            self.text(0, 10, drawing_form['title'], 0.6, 'TEXT')
        )
        
        # Build complete DXF
        dxf_content = ""
        dxf_content += self.create_header_section()
        dxf_content += self.create_tables_section()
        dxf_content += self.create_blocks_section()
        dxf_content += self.create_entities_section(self.entities)
        dxf_content += "  0\nEOF\n"
        
        return dxf_content
    
    def save_dxf(self, drawing_form: Dict, output_path: str):
        """Generate and save DXF file."""
        dxf_content = self.generate_dxf(drawing_form)
        
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_file, 'w') as f:
            f.write(dxf_content)
        
        print(f"✅ DXF file saved: {output_file}")
        return output_file


# Example usage
if __name__ == "__main__":
    from common_drawing_forms import CommonDrawingForms, DrawingParameters
    
    # Create parameters
    params = DrawingParameters(
        span_length=14.0,
        number_of_spans=3,
        carriage_width=7.5,
        footpath_width=1.5,
        rtl=100.500,
        hfl=98.200,
        bed_level=95.000,
        foundation_level=90.000,
        agl=96.500,
        pier_width=1.2,
        pier_depth=8.0,
        pier_cap_height=0.5,
        pier_cap_width=2.0,
        abutment_width=1.5,
        abutment_base_width=3.0,
        abutment_height=6.0,
        slab_thickness=0.45,
        wearing_coat_thickness=0.075,
        project_name="Sample Bridge Project",
        drawing_no="GAD-001"
    )
    
    # Generate drawing forms
    forms = CommonDrawingForms()
    gad = forms.create_gad_elevation(params)
    
    # Generate DXF
    generator = DXFGenerator()
    output_path = r"C:\Users\Rajkumar\Downloads\Dwg-Dxf-Record-Keeper\COLLECTION FROM RECORD\output\GAD_Elevation.dxf"
    generator.save_dxf(gad, output_path)
    
    print("\n✅ DXF generation complete!")
    print(f"Output: {output_path}")
